
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Apr 26 2026 13:15:17 CST (Apr 26 2026 19:15:17 UTC)

// Verification Directory fv/UART 

`timescale 1ns/1ps

module UART_rx(clk, reset, rx_data_in, rx_data_rdy, rx_data_out);
  input clk, reset, rx_data_in;
  output rx_data_rdy;
  output [7:0] rx_data_out;
  wire clk, reset, rx_data_in;
  wire rx_data_rdy;
  wire [7:0] rx_data_out;
  wire [3:0] baud_x16_count;
  wire [2:0] bit_count;
  wire [3:0] bit_duration_count;
  wire [1:0] rx_state;
  wire [7:0] rx_stored_data;
  wire baud_rate_x16_clk, edge_signal, n_10, n_151, n_152, n_153,
       n_173, n_185;
  wire n_188, n_192, n_204, n_437, n_438, n_439, n_440, n_441;
  wire n_442, n_443, n_444, n_566, n_568, n_570, n_572, n_576;
  wire n_580, n_584, n_588, n_592, n_958, n_1087, n_1088, n_1089;
  wire n_1094, n_1095, n_1096, n_1097, n_1099, n_1100, n_1102, n_1103;
  wire n_1105, n_1106, n_1110, n_1112, n_1118, n_1119, n_1120, n_1126;
  wire n_1135, n_1136, n_1137, n_1141, n_1144, n_1147, n_1148, n_1149;
  wire n_1150, n_1151, n_1152, n_1153, n_1154, n_1155, n_1156, n_1157;
  wire n_1158, n_1159, n_1160, n_1161, n_1162, n_1163, n_1164, n_1169;
  wire n_1170, n_1179, n_1184, n_1185, n_1188, n_1191, n_1194, n_1197;
  wire n_1200, n_1203, n_1210, n_1211, n_1212, n_1215, n_1220, n_1221;
  wire n_1226, n_1227, n_1232, n_1233, n_1238, n_1239, n_1244, n_1245;
  wire n_1250, n_1251, n_1256, n_1257, n_1262, n_1263, n_1266, n_1269;
  wire n_1272, n_1279, n_1280, n_1281, n_1296, n_1297, n_1298, n_1299;
  wire n_1300, n_1301, n_1302, n_1307, n_1308, n_1317, n_1318, n_1319;
  wire n_1320, n_1327, n_1328, n_1329, n_1336, n_1337, n_1338, n_1343;
  wire n_1356, n_1363, n_1364, n_1366, rx_end;
  CDN_flop baud_rate_x16_clk_reg(.clk (clk), .d (1'b0), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (n_1089), .srd (reset), .q
       (baud_rate_x16_clk));
  CDN_flop \baud_x16_count_reg[0] (.clk (clk), .d (n_566), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_x16_count[0]));
  CDN_flop \baud_x16_count_reg[1] (.clk (clk), .d (n_568), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_x16_count[1]));
  CDN_flop \baud_x16_count_reg[2] (.clk (clk), .d (n_570), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_x16_count[2]));
  CDN_flop \baud_x16_count_reg[3] (.clk (clk), .d (n_572), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_x16_count[3]));
  CDN_flop \bit_count_reg[0] (.clk (clk), .d (n_151), .sena (n_204),
       .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0), .q
       (bit_count[0]));
  CDN_flop \bit_count_reg[1] (.clk (clk), .d (n_152), .sena (n_204),
       .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0), .q
       (bit_count[1]));
  CDN_flop \bit_count_reg[2] (.clk (clk), .d (n_153), .sena (n_204),
       .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0), .q
       (bit_count[2]));
  CDN_flop \bit_duration_count_reg[0] (.clk (clk), .d (n_576), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (bit_duration_count[0]));
  CDN_flop \bit_duration_count_reg[1] (.clk (clk), .d (n_580), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (bit_duration_count[1]));
  CDN_flop \bit_duration_count_reg[2] (.clk (clk), .d (n_584), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (bit_duration_count[2]));
  CDN_flop \bit_duration_count_reg[3] (.clk (clk), .d (n_588), .sena
       (1'b1), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (bit_duration_count[3]));
  CDN_flop edge_signal_reg(.clk (clk), .d (rx_end), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0), .q
       (edge_signal));
  nand g2082 (n_1102, bit_count[0], bit_count[1]);
  or g2103 (n_1099, bit_count[0], wc);
  not gc (wc, bit_count[1]);
  or g2109 (n_1100, wc0, bit_count[1]);
  not gc0 (wc0, bit_count[0]);
  or g2115 (n_1087, baud_x16_count[1], baud_x16_count[0]);
  or g2122 (n_1110, bit_count[0], bit_count[1]);
  or g2153 (n_1088, baud_x16_count[2], n_1087);
  or g2195 (n_1103, wc1, n_1102);
  not gc1 (wc1, bit_count[2]);
  not g2551 (n_10, rx_state[0]);
  not g2552 (n_958, reset);
  or g2642 (n_1144, wc2, n_1096);
  not gc2 (wc2, rx_state[0]);
  nand g2661 (n_1150, bit_duration_count[0], bit_duration_count[1]);
  nand g2690 (n_1164, n_1099, n_1100);
  or g2817 (n_185, wc3, n_1302);
  not gc3 (wc3, n_1097);
  nand g2821 (n_1320, n_1318, n_1319);
  nand g2822 (n_592, n_1280, n_1281);
  nand g2824 (n_204, n_1137, n_1272);
  nand g2826 (n_1319, n_1149, bit_duration_count[1]);
  nand g2827 (n_192, n_1094, n_1097);
  or g2828 (n_1281, n_1279, wc4);
  not gc4 (wc4, rx_state[1]);
  nand g2829 (n_1301, n_1298, n_1299);
  or g2830 (n_1300, n_1297, wc5);
  not gc5 (wc5, rx_state[1]);
  nand g2831 (n_1279, n_1144, reset);
  or g2832 (n_1272, wc6, n_1126);
  not gc6 (wc6, n_1103);
  nand g2833 (n_1149, n_1118, n_1147);
  nand g2834 (n_1329, n_1327, n_1328);
  or g2835 (n_1299, n_1296, wc7);
  not gc7 (wc7, rx_state[0]);
  or g2836 (n_1297, n_1103, n_1126);
  or g2837 (n_1097, n_1144, wc8);
  not gc8 (wc8, rx_state[1]);
  not g2838 (n_173, n_1097);
  or g2839 (n_1318, n_1317, wc9);
  not gc9 (wc9, bit_duration_count[0]);
  nand g2840 (n_188, n_1137, n_1126);
  nand g2841 (n_1308, n_1307, n_1147);
  nand g2842 (n_1338, n_1336, n_1337);
  or g2843 (n_1307, n_1118, wc10);
  not gc10 (wc10, bit_duration_count[0]);
  or g2844 (n_1317, wc11, bit_duration_count[1]);
  not gc11 (wc11, n_1120);
  nand g2845 (n_1327, n_1151, n_1120);
  or g2846 (n_1296, wc12, n_1094);
  not gc12 (wc12, n_1148);
  or g2847 (n_1147, wc13, bit_duration_count[0]);
  not gc13 (wc13, n_1120);
  nand g2849 (n_1336, n_1152, n_1120);
  or g2850 (n_1337, n_1118, wc14);
  not gc14 (wc14, bit_duration_count[3]);
  nand g2855 (n_442, n_1238, n_1239);
  nand g2856 (n_444, n_1262, n_1263);
  nand g2858 (n_440, n_1256, n_1257);
  nand g2861 (n_439, n_1232, n_1233);
  nand g2862 (n_441, n_1250, n_1251);
  or g2865 (n_1126, rx_state[0], n_1096);
  nand g2866 (n_443, n_1244, n_1245);
  nand g2867 (n_438, n_1226, n_1227);
  nand g2868 (n_1118, n_1153, reset);
  nand g2870 (n_1154, n_1220, n_1221);
  nand g2871 (n_1262, n_1161, rx_stored_data[0]);
  nand g2872 (n_1256, n_1160, rx_stored_data[4]);
  nand g2873 (n_1089, n_1269, reset);
  nand g2874 (n_1250, n_1159, rx_stored_data[3]);
  or g2875 (n_1148, wc15, rx_data_in);
  not gc15 (wc15, n_1141);
  nand g2876 (n_1244, n_1158, rx_stored_data[1]);
  nand g2877 (n_1120, n_1211, n_1212);
  nand g2878 (n_1238, n_1157, rx_stored_data[2]);
  nand g2879 (n_1232, n_1156, rx_stored_data[5]);
  nand g2880 (n_1226, n_1155, rx_stored_data[6]);
  nand g2881 (n_1152, n_1141, n_1215);
  or g2883 (n_1280, n_1141, n_1136);
  nand g2884 (n_1158, n_1191, n_1135);
  nand g2885 (n_1156, n_1105, n_1191);
  nand g2886 (n_1159, n_1135, n_1194);
  nand g2887 (n_1157, n_1188, n_1135);
  nand g2888 (n_1155, n_1105, n_1188);
  or g2889 (n_1141, n_1095, bit_duration_count[3]);
  nand g2890 (n_153, n_1184, n_1185);
  nand g2891 (n_1160, n_1105, n_1197);
  nand g2892 (n_1161, n_1197, n_1135);
  or g2895 (n_1203, n_1095, wc16);
  not gc16 (wc16, bit_duration_count[3]);
  nand g2896 (n_1215, n_1095, bit_duration_count[3]);
  nand g2897 (n_1163, n_1088, n_1266);
  or g2899 (n_1227, n_1099, n_1112);
  or g2900 (n_1233, n_1100, n_1112);
  or g2901 (n_1239, n_1099, n_1106);
  or g2902 (n_1251, n_1102, n_1106);
  or g2903 (n_1257, n_1110, n_1112);
  nand g2904 (n_1221, n_1103, rx_stored_data[7]);
  or g2905 (n_1220, n_1103, wc17);
  not gc17 (wc17, rx_data_in);
  or g2906 (n_1263, n_1106, n_1110);
  or g2907 (n_1298, n_1137, rx_data_in);
  nand g2908 (n_1343, n_1088, baud_x16_count[3]);
  or g2909 (n_1269, n_1088, baud_x16_count[3]);
  nand g2910 (n_1153, baud_rate_x16_clk, n_1170);
  or g2911 (n_1245, n_1100, n_1106);
  or g2912 (n_1095, n_1179, wc18);
  not gc18 (wc18, bit_duration_count[0]);
  or g2913 (n_1170, n_1169, rx_state[1]);
  nand g2914 (n_1363, n_1150, bit_duration_count[2]);
  or g2915 (n_1364, n_1150, bit_duration_count[2]);
  nand g2916 (n_1151, n_1363, n_1364);
  or g2917 (n_1212, n_1210, wc19);
  not gc19 (wc19, rx_state[1]);
  nand g2918 (n_1162, n_1087, n_1200);
  or g2919 (n_1136, n_1356, n_1210);
  nand g2920 (n_1266, n_1087, baud_x16_count[2]);
  or g2921 (n_1112, n_1135, wc20);
  not gc20 (wc20, rx_data_in);
  or g2922 (n_1184, n_1102, n_1105);
  or g2923 (n_1185, wc21, n_1135);
  not gc21 (wc21, n_1102);
  nand g2924 (n_1188, n_1099, rx_state[1]);
  or g2925 (n_1137, n_1094, rx_state[0]);
  nand g2926 (n_1191, n_1100, rx_state[1]);
  nand g2927 (n_1194, n_1102, rx_state[1]);
  nand g2928 (n_1197, n_1110, rx_state[1]);
  or g2930 (n_1105, wc22, bit_count[2]);
  not gc22 (wc22, rx_state[1]);
  nand g2931 (n_1135, rx_state[1], bit_count[2]);
  or g2932 (n_1356, rx_data_in, wc23);
  not gc23 (wc23, rx_state[0]);
  nand g2933 (n_1210, baud_rate_x16_clk, reset);
  nand g2934 (n_1179, bit_duration_count[2], bit_duration_count[1]);
  or g2935 (n_1094, wc24, rx_state[1]);
  not gc24 (wc24, baud_rate_x16_clk);
  nand g2940 (n_1169, rx_data_in, rx_state[0]);
  nand g2941 (n_1200, baud_x16_count[0], baud_x16_count[1]);
  and g2942 (n_151, rx_state[1], wc25);
  not gc25 (wc25, bit_count[0]);
  and g2943 (n_1366, rx_end, wc26);
  not gc26 (wc26, edge_signal);
  and g2944 (n_152, n_1164, rx_state[1]);
  nor g2946 (n_566, n_1089, baud_x16_count[0]);
  and g2947 (n_437, n_1154, rx_state[1]);
  or g2949 (n_1106, wc27, n_1105);
  not gc27 (wc27, rx_data_in);
  or g2950 (n_1211, n_1136, wc28);
  not gc28 (wc28, n_1095);
  or g2951 (n_1096, n_1203, wc29);
  not gc29 (wc29, baud_rate_x16_clk);
  or g2953 (n_1328, wc30, n_1118);
  not gc30 (wc30, bit_duration_count[2]);
  or g2954 (n_572, wc31, n_1089);
  not gc31 (wc31, n_1343);
  and g2955 (n_570, n_1163, wc32);
  not gc32 (wc32, n_1089);
  and g2956 (n_568, n_1162, wc33);
  not gc33 (wc33, n_1089);
  or g2957 (n_1119, wc34, n_1097);
  not gc34 (wc34, reset);
  or g2958 (n_1302, wc35, n_1301);
  not gc35 (wc35, n_1300);
  or g2959 (n_584, wc36, n_1329);
  not gc36 (wc36, n_1119);
  or g2960 (n_576, wc37, n_1308);
  not gc37 (wc37, n_1119);
  or g2961 (n_588, wc38, n_1338);
  not gc38 (wc38, n_1119);
  or g2962 (n_580, wc39, n_1320);
  not gc39 (wc39, n_1119);
  CDN_flop \rx_data_out_reg[0] (.clk (clk), .d (rx_stored_data[0]),
       .sena (n_173), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd
       (1'b0), .q (rx_data_out[0]));
  CDN_flop \rx_data_out_reg[1] (.clk (clk), .d (rx_stored_data[1]),
       .sena (n_173), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd
       (1'b0), .q (rx_data_out[1]));
  CDN_flop \rx_data_out_reg[2] (.clk (clk), .d (rx_stored_data[2]),
       .sena (n_173), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd
       (1'b0), .q (rx_data_out[2]));
  CDN_flop \rx_data_out_reg[3] (.clk (clk), .d (rx_stored_data[3]),
       .sena (n_173), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd
       (1'b0), .q (rx_data_out[3]));
  CDN_flop \rx_data_out_reg[4] (.clk (clk), .d (rx_stored_data[4]),
       .sena (n_173), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd
       (1'b0), .q (rx_data_out[4]));
  CDN_flop \rx_data_out_reg[5] (.clk (clk), .d (rx_stored_data[5]),
       .sena (n_173), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd
       (1'b0), .q (rx_data_out[5]));
  CDN_flop \rx_data_out_reg[6] (.clk (clk), .d (rx_stored_data[6]),
       .sena (n_173), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd
       (1'b0), .q (rx_data_out[6]));
  CDN_flop \rx_data_out_reg[7] (.clk (clk), .d (rx_stored_data[7]),
       .sena (n_173), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd
       (1'b0), .q (rx_data_out[7]));
  CDN_flop rx_data_rdy_reg(.clk (clk), .d (n_1366), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0), .q
       (rx_data_rdy));
  CDN_flop rx_end_reg(.clk (clk), .d (rx_state[1]), .sena (n_192),
       .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0), .q
       (rx_end));
  CDN_flop \rx_state_reg[0] (.clk (clk), .d (n_10), .sena (n_185),
       .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0), .q
       (rx_state[0]));
  CDN_flop \rx_state_reg[1] (.clk (clk), .d (n_592), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (rx_state[1]));
  CDN_flop \rx_stored_data_reg[0] (.clk (clk), .d (n_444), .sena
       (n_188), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0),
       .q (rx_stored_data[0]));
  CDN_flop \rx_stored_data_reg[1] (.clk (clk), .d (n_443), .sena
       (n_188), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0),
       .q (rx_stored_data[1]));
  CDN_flop \rx_stored_data_reg[2] (.clk (clk), .d (n_442), .sena
       (n_188), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0),
       .q (rx_stored_data[2]));
  CDN_flop \rx_stored_data_reg[3] (.clk (clk), .d (n_441), .sena
       (n_188), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0),
       .q (rx_stored_data[3]));
  CDN_flop \rx_stored_data_reg[4] (.clk (clk), .d (n_440), .sena
       (n_188), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0),
       .q (rx_stored_data[4]));
  CDN_flop \rx_stored_data_reg[5] (.clk (clk), .d (n_439), .sena
       (n_188), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0),
       .q (rx_stored_data[5]));
  CDN_flop \rx_stored_data_reg[6] (.clk (clk), .d (n_438), .sena
       (n_188), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0),
       .q (rx_stored_data[6]));
  CDN_flop \rx_stored_data_reg[7] (.clk (clk), .d (n_437), .sena
       (n_188), .aclr (1'b0), .apre (1'b0), .srl (n_958), .srd (1'b0),
       .q (rx_stored_data[7]));
endmodule

module UART_tx(clk, reset, tx_start, tx_rdy, tx_data_in, tx_data_out);
  input clk, reset, tx_start;
  input [7:0] tx_data_in;
  output tx_rdy, tx_data_out;
  wire clk, reset, tx_start;
  wire [7:0] tx_data_in;
  wire tx_rdy, tx_data_out;
  wire [7:0] baud_count;
  wire [2:0] data_index;
  wire [1:0] tx_state;
  wire [7:0] stored_data;
  wire [7:0] reg_data;
  wire baud_rate_clk, clean, data_index_reset, edge_signal, n_28, n_80,
       n_85, n_89;
  wire n_90, n_91, n_92, n_141, n_168, n_222, n_369, n_436;
  wire n_438, n_440, n_442, n_444, n_446, n_448, n_450, n_454;
  wire n_463, n_467, n_471, n_475, n_479, n_827, n_828, n_837;
  wire n_861, n_862, n_865, n_866, n_868, n_869, n_872, n_874;
  wire n_875, n_880, n_881, n_882, n_883, n_884, n_885, n_886;
  wire n_887, n_888, n_889, n_890, n_891, n_892, n_893, n_898;
  wire n_899, n_904, n_905, n_910, n_911, n_916, n_917, n_920;
  wire n_925, n_926, n_931, n_932, n_937, n_938, n_943, n_944;
  wire n_949, n_950, n_957, n_958, n_959, n_964, n_965, n_972;
  wire n_973, n_974, n_985, n_986, n_987, n_988, n_989, n_995;
  wire n_1003, n_1004, n_1009, n_1010, n_1018, n_1024, n_1025, n_1066;
  wire n_1068, n_1071, n_1072, n_1073, n_1075, n_1076, n_1077, n_1078;
  wire n_1079, reg_start, start_detected, start_reset, tx_end;
  CDN_flop \baud_count_reg[0] (.clk (clk), .d (n_436), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_count[0]));
  CDN_flop \baud_count_reg[1] (.clk (clk), .d (n_438), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_count[1]));
  CDN_flop \baud_count_reg[2] (.clk (clk), .d (n_440), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_count[2]));
  CDN_flop \baud_count_reg[3] (.clk (clk), .d (n_442), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_count[3]));
  CDN_flop \baud_count_reg[4] (.clk (clk), .d (n_444), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_count[4]));
  CDN_flop \baud_count_reg[5] (.clk (clk), .d (n_446), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_count[5]));
  CDN_flop \baud_count_reg[6] (.clk (clk), .d (n_448), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_count[6]));
  CDN_flop \baud_count_reg[7] (.clk (clk), .d (n_450), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (baud_count[7]));
  CDN_flop baud_rate_clk_reg(.clk (clk), .d (1'b0), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (n_168), .srd (reset), .q
       (baud_rate_clk));
  CDN_flop clean_reg(.clk (clk), .d (n_141), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (clean));
  CDN_flop \data_index_reg[0] (.clk (clk), .d (n_90), .sena
       (baud_rate_clk), .aclr (1'b0), .apre (1'b0), .srl (n_89), .srd
       (1'b0), .q (data_index[0]));
  CDN_flop \data_index_reg[1] (.clk (clk), .d (n_91), .sena
       (baud_rate_clk), .aclr (1'b0), .apre (1'b0), .srl (n_89), .srd
       (1'b0), .q (data_index[1]));
  CDN_flop \data_index_reg[2] (.clk (clk), .d (n_92), .sena
       (baud_rate_clk), .aclr (1'b0), .apre (1'b0), .srl (n_89), .srd
       (1'b0), .q (data_index[2]));
  CDN_flop data_index_reset_reg(.clk (clk), .d (n_467), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (data_index_reset));
  CDN_flop edge_signal_reg(.clk (clk), .d (tx_end), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (n_80), .srd (1'b0), .q
       (edge_signal));
  not g12 (n_80, reset);
  not g52 (n_90, data_index[0]);
  or g909 (n_85, wc40, clean);
  not gc40 (wc40, reset);
  not g929 (n_28, n_85);
  or g934 (n_89, wc41, data_index_reset);
  not gc41 (wc41, reset);
  or g1118 (n_862, n_865, tx_state[0]);
  or g1121 (n_866, baud_count[1], baud_count[0]);
  nand g1136 (n_869, data_index[0], data_index[1]);
  or g1155 (n_865, tx_state[1], wc42);
  not gc42 (wc42, baud_rate_clk);
  or g1166 (n_222, n_85, tx_start);
  or g1169 (n_827, n_866, baud_count[2]);
  or g1261 (n_881, n_868, baud_count[7]);
  or g1389 (n_868, baud_count[6], n_885);
  or g1412 (n_454, n_989, wc43);
  not gc43 (wc43, reset);
  or g1415 (n_438, n_1004, n_168);
  or g1423 (n_442, n_1010, n_168);
  nand g1427 (n_988, n_985, n_986);
  nand g1429 (n_168, n_881, reset);
  nand g1430 (n_886, n_995, n_868);
  or g1431 (n_986, wc44, n_861);
  not gc44 (wc44, n_891);
  or g1432 (n_467, n_959, wc45);
  not gc45 (wc45, reset);
  nand g1433 (n_1018, n_868, baud_count[7]);
  nand g1434 (n_891, n_964, n_965);
  nand g1435 (n_995, n_885, baud_count[6]);
  or g1439 (n_885, n_828, baud_count[5]);
  or g1440 (n_964, wc46, data_index[1]);
  not gc46 (wc46, n_880);
  nand g1441 (n_965, n_837, data_index[1]);
  nand g1443 (n_1066, n_828, baud_count[5]);
  nand g1444 (n_882, n_885, n_1066);
  or g1445 (n_475, n_1025, wc47);
  not gc47 (wc47, reset);
  nand g1446 (n_958, n_957, n_872);
  or g1447 (n_892, wc48, n_974);
  not gc48 (wc48, n_872);
  nand g1448 (n_1010, n_1009, n_875);
  or g1449 (n_872, n_950, wc49);
  not gc49 (wc49, data_index[2]);
  nand g1450 (n_837, n_937, n_938);
  nand g1452 (n_1068, n_875, baud_count[4]);
  nand g1453 (n_883, n_828, n_1068);
  or g1454 (n_828, n_875, baud_count[4]);
  nand g1455 (n_880, n_931, n_932);
  nand g1456 (n_1025, n_1024, n_944);
  nand g1459 (n_974, n_972, n_973);
  or g1462 (n_950, n_949, tx_state[0]);
  or g1463 (n_973, n_862, wc50);
  not gc50 (wc50, start_detected);
  or g1464 (n_937, wc51, data_index[2]);
  not gc51 (wc51, n_889);
  nand g1465 (n_938, n_890, data_index[2]);
  nand g1466 (n_1024, n_862, start_reset);
  nand g1467 (n_932, n_888, data_index[2]);
  nand g1468 (n_463, n_874, n_926);
  nand g1469 (n_893, n_943, n_944);
  or g1470 (n_875, n_827, baud_count[3]);
  nand g1471 (n_1009, n_827, baud_count[3]);
  or g1472 (n_931, wc52, data_index[2]);
  not gc52 (wc52, n_887);
  nand g1473 (n_888, n_904, n_905);
  nand g1474 (n_889, n_910, n_911);
  nand g1475 (n_1004, n_866, n_1003);
  nand g1476 (n_887, n_898, n_899);
  nand g1477 (n_1071, n_869, data_index[2]);
  or g1478 (n_1072, n_869, data_index[2]);
  nand g1479 (n_92, n_1071, n_1072);
  nand g1480 (n_890, n_916, n_917);
  or g1481 (n_944, n_861, wc53);
  not gc53 (wc53, tx_state[0]);
  nand g1482 (n_943, n_865, tx_end);
  or g1483 (n_926, n_925, wc54);
  not gc54 (wc54, reset);
  or g1484 (n_874, n_920, wc55);
  not gc55 (wc55, reset);
  nand g1485 (n_957, n_865, data_index_reset);
  or g1486 (n_949, n_861, n_869);
  or g1487 (n_987, wc56, n_369);
  not gc56 (wc56, baud_rate_clk);
  nand g1488 (n_1073, n_866, baud_count[2]);
  nand g1490 (n_884, n_1073, n_827);
  nand g1491 (n_1003, baud_count[1], baud_count[0]);
  or g1492 (n_985, baud_rate_clk, wc57);
  not gc57 (wc57, tx_data_out);
  or g1493 (n_920, start_reset, wc58);
  not gc58 (wc58, reg_start);
  or g1494 (n_972, baud_rate_clk, wc59);
  not gc59 (wc59, tx_state[0]);
  or g1495 (n_898, data_index[0], wc60);
  not gc60 (wc60, stored_data[0]);
  nand g1496 (n_899, data_index[0], stored_data[1]);
  nand g1497 (n_861, tx_state[1], baud_rate_clk);
  or g1498 (n_904, data_index[0], wc61);
  not gc61 (wc61, stored_data[4]);
  nand g1503 (n_91, n_1076, n_1077);
  nand g1506 (n_369, n_1078, n_1079);
  nand g1507 (n_905, data_index[0], stored_data[5]);
  or g1508 (n_910, data_index[0], wc62);
  not gc62 (wc62, stored_data[2]);
  nand g1509 (n_911, data_index[0], stored_data[3]);
  or g1510 (n_916, data_index[0], wc63);
  not gc63 (wc63, stored_data[6]);
  nand g1511 (n_917, data_index[0], stored_data[7]);
  or g1512 (n_925, start_reset, wc64);
  not gc64 (wc64, start_detected);
  and g1513 (n_1075, tx_end, wc65);
  not gc65 (wc65, edge_signal);
  nor g1514 (n_141, n_874, start_detected);
  and g1515 (n_479, n_893, reset);
  and g1516 (n_471, n_892, reset);
  nor g1520 (n_436, n_168, baud_count[0]);
  or g1525 (n_1078, wc66, tx_state[0]);
  not gc66 (wc66, tx_state[1]);
  or g1526 (n_1079, tx_state[1], wc67);
  not gc67 (wc67, tx_state[0]);
  or g1527 (n_1076, wc68, data_index[0]);
  not gc68 (wc68, data_index[1]);
  or g1528 (n_1077, data_index[1], wc69);
  not gc69 (wc69, data_index[0]);
  or g1529 (n_959, n_958, wc70);
  not gc70 (wc70, n_862);
  or g1531 (n_989, wc71, n_988);
  not gc71 (wc71, n_987);
  or g1532 (n_450, wc72, n_168);
  not gc72 (wc72, n_1018);
  and g1533 (n_448, n_886, wc73);
  not gc73 (wc73, n_168);
  and g1534 (n_444, n_883, wc74);
  not gc74 (wc74, n_168);
  and g1535 (n_440, n_884, wc75);
  not gc75 (wc75, n_168);
  and g1536 (n_446, n_882, wc76);
  not gc76 (wc76, n_168);
  CDN_flop \reg_data_reg[0] (.clk (clk), .d (tx_data_in[0]), .sena
       (tx_start), .aclr (1'b0), .apre (1'b0), .srl (n_85), .srd
       (1'b0), .q (reg_data[0]));
  CDN_flop \reg_data_reg[1] (.clk (clk), .d (tx_data_in[1]), .sena
       (tx_start), .aclr (1'b0), .apre (1'b0), .srl (n_85), .srd
       (1'b0), .q (reg_data[1]));
  CDN_flop \reg_data_reg[2] (.clk (clk), .d (tx_data_in[2]), .sena
       (tx_start), .aclr (1'b0), .apre (1'b0), .srl (n_85), .srd
       (1'b0), .q (reg_data[2]));
  CDN_flop \reg_data_reg[3] (.clk (clk), .d (tx_data_in[3]), .sena
       (tx_start), .aclr (1'b0), .apre (1'b0), .srl (n_85), .srd
       (1'b0), .q (reg_data[3]));
  CDN_flop \reg_data_reg[4] (.clk (clk), .d (tx_data_in[4]), .sena
       (tx_start), .aclr (1'b0), .apre (1'b0), .srl (n_85), .srd
       (1'b0), .q (reg_data[4]));
  CDN_flop \reg_data_reg[5] (.clk (clk), .d (tx_data_in[5]), .sena
       (tx_start), .aclr (1'b0), .apre (1'b0), .srl (n_85), .srd
       (1'b0), .q (reg_data[5]));
  CDN_flop \reg_data_reg[6] (.clk (clk), .d (tx_data_in[6]), .sena
       (tx_start), .aclr (1'b0), .apre (1'b0), .srl (n_85), .srd
       (1'b0), .q (reg_data[6]));
  CDN_flop \reg_data_reg[7] (.clk (clk), .d (tx_data_in[7]), .sena
       (tx_start), .aclr (1'b0), .apre (1'b0), .srl (n_85), .srd
       (1'b0), .q (reg_data[7]));
  CDN_flop reg_start_reg(.clk (clk), .d (1'b0), .sena (1'b0), .aclr
       (1'b0), .apre (1'b0), .srl (n_222), .srd (n_28), .q (reg_start));
  CDN_flop start_detected_reg(.clk (clk), .d (n_463), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (start_detected));
  CDN_flop start_reset_reg(.clk (clk), .d (n_475), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (start_reset));
  CDN_flop \stored_data_reg[0] (.clk (clk), .d (reg_data[0]), .sena
       (n_141), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (stored_data[0]));
  CDN_flop \stored_data_reg[1] (.clk (clk), .d (reg_data[1]), .sena
       (n_141), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (stored_data[1]));
  CDN_flop \stored_data_reg[2] (.clk (clk), .d (reg_data[2]), .sena
       (n_141), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (stored_data[2]));
  CDN_flop \stored_data_reg[3] (.clk (clk), .d (reg_data[3]), .sena
       (n_141), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (stored_data[3]));
  CDN_flop \stored_data_reg[4] (.clk (clk), .d (reg_data[4]), .sena
       (n_141), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (stored_data[4]));
  CDN_flop \stored_data_reg[5] (.clk (clk), .d (reg_data[5]), .sena
       (n_141), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (stored_data[5]));
  CDN_flop \stored_data_reg[6] (.clk (clk), .d (reg_data[6]), .sena
       (n_141), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (stored_data[6]));
  CDN_flop \stored_data_reg[7] (.clk (clk), .d (reg_data[7]), .sena
       (n_141), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0),
       .q (stored_data[7]));
  CDN_flop tx_data_out_reg(.clk (clk), .d (n_454), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (tx_data_out));
  CDN_flop tx_end_reg(.clk (clk), .d (n_479), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (tx_end));
  CDN_flop tx_rdy_reg(.clk (clk), .d (n_1075), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (n_80), .srd (1'b0), .q (tx_rdy));
  CDN_flop \tx_state_reg[0] (.clk (clk), .d (n_471), .sena (1'b1),
       .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q
       (tx_state[0]));
  CDN_flop \tx_state_reg[1] (.clk (clk), .d (n_369), .sena
       (baud_rate_clk), .aclr (1'b0), .apre (1'b0), .srl (n_80), .srd
       (1'b0), .q (tx_state[1]));
endmodule

module UART(clk, reset, tx_start, tx_rdy, rx_data_rdy, data_in,
     data_out, rx, tx);
  input clk, reset, tx_start, rx;
  input [7:0] data_in;
  output tx_rdy, rx_data_rdy, tx;
  output [7:0] data_out;
  wire clk, reset, tx_start, rx;
  wire [7:0] data_in;
  wire tx_rdy, rx_data_rdy, tx;
  wire [7:0] data_out;
  UART_rx receiver(.clk (clk), .reset (reset), .rx_data_in (rx),
       .rx_data_rdy (rx_data_rdy), .rx_data_out (data_out));
  UART_tx transmitter(.clk (clk), .reset (reset), .tx_start (tx_start),
       .tx_rdy (tx_rdy), .tx_data_in (data_in), .tx_data_out (tx));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
